spring:
  application:
    name: Microservice-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sumitranaware/microservice-ecommerce-config-server
          username: sumitranaware
          default-label: master

server:
  port: 8788
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka